package com.factubelgica.api.contexts.billing.services;

import com.factubelgica.api.contexts.billing.dtos.InvoiceCreateRequest;
import com.factubelgica.api.contexts.billing.errors.ErrorCreatingInvoice;
import com.factubelgica.api.contexts.billing.models.Invoice;
import com.factubelgica.api.contexts.billing.models.InvoiceItem;
import com.factubelgica.api.contexts.billing.persistance.IInvoiceRepository;
import com.factubelgica.api.contexts.catalog.models.Product;
import com.factubelgica.api.contexts.catalog.persistance.IProductRepository;
import com.factubelgica.api.contexts.clients.models.Client;
import com.factubelgica.api.contexts.clients.persistance.IClientRepository;
import com.factubelgica.api.shared.core.UUIDv7;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;

@Service
@RequiredArgsConstructor
public class InvoiceCreate {

  private static final BigDecimal DEFAULT_VAT_RATE = new BigDecimal("0.21");

  private final IInvoiceRepository invoiceRepository;
  private final IClientRepository clientRepository;
  private final IProductRepository productRepository;
  private final UUIDv7 uuidv7;

  public Invoice execute(InvoiceCreateRequest req, UUID authUserId) {
    // 1. Resolve client and snapshot the latest infoId
    Client client = clientRepository.findById(req.clientId())
        .orElseThrow(() -> new ErrorCreatingInvoice(
            "Client not found with ID: " + req.clientId()));

    if (!client.getActive()) {
      throw new ErrorCreatingInvoice("Client is inactive: " + req.clientId());
    }

    Integer infoId = client.getInfoId();

    // 2. Resolve and snapshot each product item
    List<InvoiceItem> items = new ArrayList<>();
    for (var itemReq : req.items()) {
      Product product = productRepository.findById(itemReq.productId())
          .orElseThrow(() -> new ErrorCreatingInvoice(
              "Product not found with ID: " + itemReq.productId()));

      if (!product.getActive()) {
        throw new ErrorCreatingInvoice("Product is inactive: " + itemReq.productId());
      }

      items.add(new InvoiceItem(
          null,                      // itemId — generated by DB
          product.getProductId(),
          itemReq.quantity(),
          product.getDescription(),  // snapshot description
          product.getNetPrice()      // snapshot price
      ));
    }

    // 3. Apply VAT rate — use request value or fall back to default 21%
    BigDecimal vatRate = (req.vatRate() != null) ? req.vatRate() : DEFAULT_VAT_RATE;

    // 4. Build the Invoice domain model
    Invoice invoice = new Invoice(
        uuidv7.generate(),
        infoId,
        authUserId,
        null,            // invoiceNumber — set by DB trigger
        LocalDate.now(),
        req.dueDate(),
        vatRate,
        null,            // paymentDate — null until status becomes Pagado
        "Pendiente",
        null,            // created — set by DB
        items
    );

    // 5. Persist and return
    return invoiceRepository.save(invoice)
        .orElseThrow(() -> new ErrorCreatingInvoice("Invoice could not be saved"));
  }
}
